services:
  - type: web
    name: sellerapp
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
